logging:
  level:
    root: INFO

spring:
  application:
    name: rohlik-assignment-backend

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 80
  servlet:
    context-path: /${spring.application.name}
